import Head from 'next/head'
import style from "../styles/Layout.module.css"
// import styleGlobal from "../styles/globals.css"
import Link from "next/link"
import {useRouter} from "next/router"


export default function Layout ({children,  title}){

  const router = useRouter()

    return (<>
     <Head>
        <title>titulo personalizado si no existe toma el del componente padre</title>
        <meta name="description" content="Generated by create next app" />
          </Head>
      <main >
        <div>
          <ul>
            <li>
          <Link href="/faq">Faq</Link>
          </li>
          <li>
          <Link href="/about">About</Link>
          </li>
         
          <li>
          <Link href="/level/anidado/anidado">Este es un link</Link>
          </li>
          </ul>
        </div>
         <h1>Mi web en next sas</h1>

         <button onClick={() =>  router.push("level/anidado/anidado/2")}>Navegar de forma programatica</button>
        
      </main>
    </>

    )
}