import Head from "next/head";
import style from "../styles/Layout.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import Nav from "./personajes";
import Header from "./Header";
import Footer from "./Footer";

export default function Layout({ children, title, data }) {
  const router = useRouter();
console.log(data);
  return (
    <>
      <Head>
        <title>Proyecto Rick y Morty | Victor Alfonso Ruiz Reyes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <Header></Header>
     
     <div className="w-full flex justify-between px-[16px] py-[42px]">
      <nav className="w-[30vw]">
        <h2 className="color-[#1F2937] text-[24px] font-[700] mb-[24px]">
          Rick and Morty list
        </h2>

        <Nav info={data} mensaje="Hola mundo" />
      </nav>
      <main className="w-full px-[16px] py-[42px]">
        {children}
      </main>
      </div>
      <Footer />

    </>
  );
}
