import Head from "next/head";
import style from "../styles/Layout.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import Nav from "./personajes";
import Header from "./Header";
import Footer from "./Footer";
import SearchCharacter from "./SearchCharacter";

export default function Layout({ children, title, data }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Proyecto Rick y Morty | Victor Alfonso Ruiz Reyes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>

      <div className="w-full flex gap-5 px-[16px] py-[42px]">
        <nav className="w-[30vw]">
          <SearchCharacter></SearchCharacter>

          <Nav info={data} mensaje="Hola mundo" />
        </nav>
        <main className="w-full px-[30px] py-[42px]">{children}</main>
      </div>
      <Footer />
    </>
  );
}
